# How to build an Docker image for the dataflow using Google Cloud Build.

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_BUCKET}/dataflow:$TAG_NAME", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_BUCKET}/dataflow:$TAG_NAME"]

substitutions:
  _BUCKET: default_bucket

images:
  - "gcr.io/$PROJECT_ID/${_BUCKET}/dataflow:$TAG_NAME"
