[tool.poetry]
name = "dataflow"
package-mode = false

[tool.poetry.dependencies]
python = "=3.11.9"
apache-beam = {extras = ["gcp"], version = "^2.55.1"}
structlog = "^24.1.0"
structlog-gcp = "^0.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"